npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=akogqyf88.hotishop.com --spaIds="147010" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=chicovel380.zenshopin.com --spaIds="147035,146964" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=ugfiqqym490.zenshopin.com --spaIds="146980" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=pdpiuoiy367.zenshopin.com --spaIds="146982" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=lrkdeppp092.zenshopin.com --spaIds="146988" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=jleisltw578.zenshopin.com --spaIds="146917" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=sttbbfkn046.zenshopin.com --spaIds="15846,40946" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=exfoukti548.zenshopin.com --spaIds="146974,146978" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=llmdeygb382.zenshopin.com --spaIds="143887,147028" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=kkcxfeki574.zenshopin.com --spaIds="147026" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=btgzuctl987.zenshopin.com --spaIds="14320,16440,22645,26100" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=lcwchwle807.zenshopin.com --spaIds="97704,147030" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=ttshhpye299.zenshopin.com --spaIds="16458,21517,62290" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=glodjouu144.zenshopin.com --spaIds="22676" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=zlchhheg632.zenshopin.com --spaIds="7290,24329" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=yfbxaick060.zenshopin.com --spaIds="144362" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=fwulttjd369.zenshopin.com --spaIds="18479,18480" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=uihqlsyl095.zenshopin.com --spaIds="144376" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=uedtbxes052.zenshopin.com --spaIds="14771,125504" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=oghgyyta232.zenshopin.com --spaIds="16498,16499" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=proovmsm732.zenshopin.com --spaIds="122987" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=lmqiznyw981.zenshopin.com --spaIds="125625" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=fooijrat295.zenshopin.com --spaIds="147102" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=rvtemjig308.zenshopin.com --spaIds="146933,146935" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=uoqaiywx684.zenshopin.com --spaIds="146931" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=fdinojkr334.zenshopin.com --spaIds="146919,146927,146928,146925" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=hbqtxrrp556.zenshopin.com --spaIds="146943" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=tfohbehc488.zenshopin.com --spaIds="146949" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=ltmynxtg66.hotishop.com --spaIds="146996" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=lkrlygmt62.hotishop.com --spaIds="147019" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=bgkkptubw10.hotishop.com --spaIds="147008,147009" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=dfgvecv67.hotishop.com --spaIds="147013" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=rmpdmyo21.hotishop.com --spaIds="28100" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=blejopgqa55.hotishop.com --spaIds="135755" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=qewpfmm88.hotishop.com --spaIds="147014" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=dwjngvxrc33.hotishop.com --spaIds="147075" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=wwukwhi74.hotishop.com --spaIds="79107" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=nkbkyuu36.hotishop.com --spaIds="146990" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=fwjhhfau89.wshopon.com --spaIds="146994" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=tnkyamly37.hotishop.com --spaIds="147024" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=rsswugpt88.hotishop.com --spaIds="124807,146152" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=kehvvbtq38.hotishop.com --spaIds="146215" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=rwmjmruh74.hotishop.com --spaIds="146247" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=cjqnjhw29.hotishop.com --spaIds="146355" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=rlgvqbdd70.hotishop.com --spaIds="129792" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=qklsbocv69.hotishop.com --spaIds="146957" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=bdmpxkkii44.hotishop.com --spaIds="123878" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=aovtzusxr39.hotishop.com --spaIds="145831" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=mxmpvxmim77.hotishop.com --spaIds="145822" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=tqhwsldfm37.hotishop.com --spaIds="146206" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=zmvpscoom31.hotishop.com --spaIds="124160" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=fwjtnhl21.hotishop.com --spaIds="144624" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=ceukudk75.hotishop.com --spaIds="145840" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=tvfcgnsh11.hotishop.com --spaIds="146716" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=kwbfwtmw68.hotishop.com --spaIds="124923" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=moxiqfvs96.hotishop.com --spaIds="144632,144633" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=vhyknqpw96.hotishop.com --spaIds="146202,146203" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=dnsyxtji58.hotishop.com --spaIds="147021,147022" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=nxspbopt07.hotishop.com --spaIds="144660" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=opnihksv32.hotishop.com --spaIds="147016" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=viraqepy98.hotishop.com --spaIds="146525" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=yjdecppc22.hotishop.com --spaIds="146198,146224" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=tqhybfuf35.hotishop.com --spaIds="145149" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=iwkdkgss11.hotishop.com --spaIds="146111,146112" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=eyuhtbdu29.hotishop.com --spaIds="146368" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=tioulnk02.hotishop.com --spaIds="146992" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=ntxoixp56.hotishop.com --spaIds="137930" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=cyskedjli69.hotishop.com --spaIds="135507" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=lxjgqvi29.hotishop.com --spaIds="146386" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=whzrbwo07.hotishop.com --spaIds="146325" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=fitnoex21.shopnova.top --spaIds="55114" --yes=1 && \
npx ts-node ./cmd/publish-spa.ts --cmd=publishShopSpa --shop=champ3.wshopon.com --spaIds="143029" --yes=1